const TABLESIDE_AI_URL='https://tableside-ai-backend-production.up.railway.app';
const AI_BROWSER_TIMEOUT_MS=70000;
const prospectPayload=p=>({businessName:p.business,city:p.city,website:p.website,instagram:p.instagram,notes:p.notes,research:p.research||''});
async function aiPost(path,payload){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),AI_BROWSER_TIMEOUT_MS);try{const response=await fetch(`${TABLESIDE_AI_URL}${path}`,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let data={};try{data=await response.json();}catch(_){}if(!response.ok)throw new Error(data.error||`AI request failed (${response.status})`);return data;}catch(error){if(error?.name==='AbortError')throw new Error('AI request timed out. Please try again.');throw error;}finally{clearTimeout(timer);}}
async function requestProspectResearch(prospect){const data=await aiPost('/api/research-prospect',prospectPayload(prospect));if(!data.identityConfidence||!Array.isArray(data.sources))throw new Error('Research service returned an incomplete result.');return data;}
async function requestProspectAnalysis(prospect){const data=await aiPost('/api/analyze-prospect',prospectPayload(prospect));if(!data.identityConfidence)throw new Error('AI returned an incomplete prospect analysis.');return data;}
async function requestAIDraft(prospect,analysis=null){const data=await aiPost('/api/generate-draft',{...prospectPayload(prospect),analysis});if(!data.body||!data.subject)throw new Error('AI returned an incomplete draft.');return {subject:String(data.subject).trim(),body:String(data.body).trim()};}
function researchEvidence(r){return JSON.stringify({identityConfidence:r.identityConfidence,matchedBusiness:r.matchedBusiness,facts:r.facts,unknowns:r.unknowns,researchSummary:r.researchSummary,sources:r.sources});}
async function prepareProspectOutreach(prospect){const research=await requestProspectResearch(prospect);const enriched={...prospect,research:researchEvidence(research)};const analysis=await requestProspectAnalysis(enriched);const draft=await requestAIDraft(enriched,analysis);return {research,analysis,draft};}
window.requestProspectResearch=requestProspectResearch;window.requestProspectAnalysis=requestProspectAnalysis;window.requestAIDraft=requestAIDraft;window.prepareProspectOutreach=prepareProspectOutreach;
function getAppState(){if(typeof window.getTableSideState==='function')return window.getTableSideState();throw new Error('App state interface unavailable.');}
function putAppState(next){if(typeof window.replaceTableSideState==='function')return window.replaceTableSideState(next);throw new Error('App state interface unavailable.');}
function analysisText(a,research=null){const rf=research?(research.facts||[]).map(x=>`• ${x.fact}\n  Sources: ${(x.sourceUrls||[]).join(', ')}`).join('\n')||'• None source-verified':'';const rs=research?(research.sources||[]).map(x=>`• ${x.title||'Source'} — ${x.url}`).join('\n')||'• No sources returned':'';const facts=(a.verifiedFacts||[]).map(x=>`• ${x}`).join('\n')||'• None verified';const unknowns=(a.unknowns||[]).map(x=>`• ${x}`).join('\n')||'• None listed';const ideas=(a.opportunities||[]).map(x=>`• [${x.confidence||'unknown'}] ${x.idea}\n  Evidence: ${x.evidence||'Not specified'}`).join('\n')||'• None generated';return `${research?`WEB RESEARCH IDENTITY CONFIDENCE\n${research.identityConfidence}\n\nSOURCE-VERIFIED RESEARCH\n${rf}\n\nRESEARCH SOURCES\n${rs}\n\n`:''}ANALYSIS IDENTITY CONFIDENCE\n${a.identityConfidence}\n\nVERIFIED FACTS\n${facts}\n\nUNKNOWNS\n${unknowns}\n\nGROWTH OPPORTUNITIES\n${ideas}\n\nSUMMARY\n${a.researchSummary||''}`;}
async function generateAIApproval(id){const saved=getAppState();const prospect=saved?.prospects?.find(p=>p.id===id);if(!prospect)return alert('Prospect not found.');const existing=saved.approvals?.find(a=>a.prospectId===id&&['Pending','Sending'].includes(a.status));if(existing)return alert('This prospect already has an approval waiting. Review or reject it before generating another.');const box=document.getElementById('workingDraft');if(box){box.disabled=true;box.value='Researching the public business identity and sources…\n\nThen I’ll analyze the evidence and prepare a draft. Nothing is being sent.';}try{const {research,analysis,draft}=await prepareProspectOutreach(prospect);const latest=getAppState();const current=latest.prospects.find(p=>p.id===id);if(current){current.research=researchEvidence(research);current.researchResult=research;current.analysis=analysis;current.analysisUpdatedAt=new Date().toISOString();}latest.approvals||=[];latest.activity||=[];const approval={id:Date.now(),prospectId:id,action:'Source-researched AI outreach',status:'Pending',subject:draft.subject,body:draft.body,research,analysis,package:`TABLESIDE GROWTH — SOURCE-RESEARCHED OUTREACH\n\nBusiness: ${prospect.business}\n\n${analysisText(analysis,research)}\n\nSUBJECT\n${draft.subject}\n\nCUSTOMER-FACING DRAFT\n${draft.body}\n\nAUTHORIZATION\nNOT SENT. Explicit human review and authorization required.`};latest.approvals.unshift(approval);latest.selected=id;latest.selectedApproval=approval.id;latest.activity.unshift(`${new Date().toLocaleString()} — Researched public sources, analyzed evidence and prepared outreach for ${prospect.business} — NOT SENT — awaiting explicit approval`);putAppState(latest);if(box)box.value=draft.body;if(typeof showTab==='function')showTab('approvals');}catch(error){console.error('AI preparation failed:',error);if(box)box.value='';alert(`AI preparation unavailable: ${error.message}\n\nNothing was sent.`);}finally{if(box)box.disabled=false;}}
window.generateAIApproval=generateAIApproval;
window.makeDraft=function(id){return generateAIApproval(id);};