const TABLESIDE_AI_URL='https://tableside-ai-backend-production.up.railway.app';
const prospectPayload=p=>({businessName:p.business,city:p.city,website:p.website,instagram:p.instagram,notes:p.notes,research:p.research||''});
async function aiPost(path,payload){const response=await fetch(`${TABLESIDE_AI_URL}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let data={};try{data=await response.json();}catch(_){}if(!response.ok)throw new Error(data.error||`AI request failed (${response.status})`);return data;}
async function requestProspectAnalysis(prospect){const data=await aiPost('/api/analyze-prospect',prospectPayload(prospect));if(!data.identityConfidence)throw new Error('AI returned an incomplete prospect analysis.');return data;}
async function requestAIDraft(prospect,analysis=null){const data=await aiPost('/api/generate-draft',{...prospectPayload(prospect),analysis});if(!data.body||!data.subject)throw new Error('AI returned an incomplete draft.');return {subject:String(data.subject).trim(),body:String(data.body).trim()};}
async function prepareProspectOutreach(prospect){const analysis=await requestProspectAnalysis(prospect);const draft=await requestAIDraft(prospect,analysis);return {analysis,draft};}
window.requestProspectAnalysis=requestProspectAnalysis;window.requestAIDraft=requestAIDraft;window.prepareProspectOutreach=prepareProspectOutreach;
function getAppState(){if(typeof window.getTableSideState==='function')return window.getTableSideState();throw new Error('App state interface unavailable.');}
function putAppState(next){if(typeof window.replaceTableSideState==='function')return window.replaceTableSideState(next);throw new Error('App state interface unavailable.');}
function analysisText(a){const facts=(a.verifiedFacts||[]).map(x=>`• ${x}`).join('\n')||'• None verified';const unknowns=(a.unknowns||[]).map(x=>`• ${x}`).join('\n')||'• None listed';const ideas=(a.opportunities||[]).map(x=>`• [${x.confidence||'unknown'}] ${x.idea}\n  Evidence: ${x.evidence||'Not specified'}`).join('\n')||'• None generated';return `IDENTITY CONFIDENCE\n${a.identityConfidence}\n\nVERIFIED FACTS\n${facts}\n\nUNKNOWNS\n${unknowns}\n\nGROWTH OPPORTUNITIES\n${ideas}\n\nSUMMARY\n${a.researchSummary||''}`;}
async function generateAIApproval(id){const saved=getAppState();const prospect=saved?.prospects?.find(p=>p.id===id);if(!prospect)return alert('Prospect not found.');const existing=saved.approvals?.find(a=>a.prospectId===id&&['Pending','Sending'].includes(a.status));if(existing)return alert('This prospect already has an approval waiting. Review or reject it before generating another.');const box=document.getElementById('workingDraft');if(box){box.disabled=true;box.value='Analyzing prospect evidence and preparing outreach…';}try{const {analysis,draft}=await prepareProspectOutreach(prospect);const latest=getAppState();const current=latest.prospects.find(p=>p.id===id);if(current){current.analysis=analysis;current.analysisUpdatedAt=new Date().toISOString();}latest.approvals||=[];latest.activity||=[];const approval={id:Date.now(),prospectId:id,action:'Evidence-based AI outreach',status:'Pending',subject:draft.subject,body:draft.body,analysis,package:`TABLESIDE GROWTH — EVIDENCE-BASED OUTREACH\n\nBusiness: ${prospect.business}\n\n${analysisText(analysis)}\n\nSUBJECT\n${draft.subject}\n\nCUSTOMER-FACING DRAFT\n${draft.body}\n\nAUTHORIZATION\nNOT SENT. Explicit human review and authorization required.`};latest.approvals.unshift(approval);latest.selected=id;latest.selectedApproval=approval.id;latest.activity.unshift(`${new Date().toLocaleString()} — Analyzed evidence and prepared outreach for ${prospect.business} — NOT SENT — awaiting explicit approval`);putAppState(latest);if(box)box.value=draft.body;if(typeof showTab==='function')showTab('approvals');}catch(error){console.error('AI preparation failed:',error);if(box)box.value='';alert(`AI preparation unavailable: ${error.message}\n\nNothing was sent.`);}finally{if(box)box.disabled=false;}}
window.generateAIApproval=generateAIApproval;const localMakeDraft=window.makeDraft;window.makeDraft=function(id){if(typeof localMakeDraft==='function')localMakeDraft(id);return generateAIApproval(id);};