const KEY = window.TABLESIDE_STORAGE_KEY || 'tableside_growth_pwa_v1';
window.TABLESIDE_STORAGE_KEY = KEY;

let state = JSON.parse(localStorage.getItem(KEY) || 'null') || {
  prospects: [], tasks: [], approvals: [], clients: [], activity: [], revenue: 0,
  selected: null, selectedApproval: null, agent: 'STOPPED', dailyLimit: 10,
  completedToday: 0, lastDay: new Date().toISOString().slice(0, 10)
};
state.prospects ||= []; state.tasks ||= []; state.approvals ||= []; state.clients ||= []; state.activity ||= [];
state.revenue ||= 0; state.agent ||= 'STOPPED'; state.dailyLimit ||= 10; state.completedToday ||= 0;
state.lastDay ||= new Date().toISOString().slice(0, 10); state.selectedApproval ||= null;
let timer = null;

const tabs=['prospects','agent','approvals','drafts','clients','activity','control'];
const labels={prospects:'Prospects',agent:'Agent Control',approvals:'Approvals',drafts:'Draft',clients:'Clients',activity:'Activity',control:'Control & Safety'};
document.getElementById('nav').innerHTML=tabs.map(t=>`<button class="secondary" onclick="showTab('${t}')">${labels[t]}</button>`).join('');

function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
window.getTableSideState=()=>JSON.parse(JSON.stringify(state));
window.replaceTableSideState=next=>{state=next;save();};
function log(msg){state.activity.unshift(`${new Date().toLocaleString()} — ${msg}`);state.activity=state.activity.slice(0,100);save();}
function showTab(id){document.querySelectorAll('.tabs>section').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function defaultOutreachBody(p){return `Hi,\n\nI came across ${p.business} and had a quick idea that could help with customer growth.\n\nI put together a short, free audit with a few specific suggestions for the business. If you're interested, I can send it over.\n\nThanks,\nGabe\nTableSide Growth`;}
function buildInternalPackage(p,body){return `TABLESIDE GROWTH — OUTREACH PACKAGE\n\nBusiness: ${p.business}\n\nAUDIT DRAFT\n1. Identify what customers already like about ${p.business}.\n2. Pick one clear reason for a new customer to visit.\n3. Build one repeatable weekly campaign.\n4. Use customer feedback and reviews as social proof.\n5. Measure enquiries, visits/orders where trackable, saves, shares and profile actions.\n\n30-DAY TEST\nWeek 1 — Research and select strongest opportunity\nWeek 2 — Build campaign and supporting content ideas\nWeek 3 — Launch after client approval\nWeek 4 — Review response and improve\n\nOUTREACH DRAFT\n${body}\n\nSTATUS\nPrepared locally. Human approval required before anything is sent.`;}
function extractLegacyBody(payload=''){if(!payload)return '';const outreachMarker='OUTREACH DRAFT',statusMarker='STATUS';let body=payload;if(payload.includes(outreachMarker)){body=payload.split(outreachMarker)[1]||'';if(body.includes(statusMarker))body=body.split(statusMarker)[0];}return body.trim();}
function normalizeApproval(a){const p=state.prospects.find(x=>x.id===a.prospectId);if(!a.subject)a.subject=`Quick question about ${p?.business||'your business'}`;if(!a.body)a.body=extractLegacyBody(a.payload)||(p?defaultOutreachBody(p):'');if(!a.package&&a.payload)a.package=a.payload;return a;}
function addProspect(){const p={id:Date.now(),business:business.value.trim(),city:city.value.trim(),website:website.value.trim(),instagram:instagram.value.trim(),email:email.value.trim(),notes:notes.value.trim(),status:'New'};if(!p.business)return alert('Enter a business name.');state.prospects.unshift(p);['business','city','website','instagram','email','notes'].forEach(id=>document.getElementById(id).value='');log(`Added prospect: ${p.business}`);}
function setStatus(id,status){const p=state.prospects.find(x=>x.id===id);if(!p)return;p.status=status;log(`${p.business} → ${status}`);}
function selectP(id){state.selected=id;state.selectedApproval=null;save();}
function queue(id){const p=state.prospects.find(x=>x.id===id);if(!p)return;const existing=state.tasks.find(t=>t.prospectId===id&&['Queued','Working','Awaiting Approval'].includes(t.status));if(existing)return alert('This prospect already has active outreach work in the queue.');state.tasks.push({id:Date.now(),prospectId:id,task:'Prepare AI outreach draft',status:'Queued'});log(`Queued AI outreach draft for ${p.business}`);}
function makeDraft(id){const p=state.prospects.find(x=>x.id===id);if(!p)return;state.selected=id;state.selectedApproval=null;workingDraft.value=defaultOutreachBody(p);showTab('drafts');save();}
function startAgent(){resetDay();if(state.agent==='RUNNING')return;state.agent='RUNNING';log('Agent started');if(timer)clearInterval(timer);timer=setInterval(agentTick,1200);}
function pauseAgent(){state.agent='PAUSED';log('Agent paused');}
function stopAgent(){state.agent='STOPPED';if(timer){clearInterval(timer);timer=null;}log('Agent stopped');}
function emergencyStop(){state.agent='STOPPED';if(timer){clearInterval(timer);timer=null;}log('EMERGENCY STOP activated');alert('Agent stopped. It will not take another queued task until you press START AGENT.');}
function resetDay(){const d=new Date().toISOString().slice(0,10);if(state.lastDay!==d){state.lastDay=d;state.completedToday=0;}}
async function agentTick(){resetDay();if(state.agent!=='RUNNING')return;if(state.completedToday>=state.dailyLimit){stopAgent();log('Daily task limit reached');return;}const t=state.tasks.find(x=>x.status==='Queued');if(!t)return;const p=state.prospects.find(x=>x.id===t.prospectId);if(!p){t.status='Error';save();return;}t.status='Working';save();try{if(typeof window.requestAIDraft!=='function')throw new Error('AI service is not loaded');const draft=await window.requestAIDraft(p);if(state.agent==='STOPPED'){t.status='Queued';save();return;}t.status='Awaiting Approval';state.completedToday++;state.approvals.unshift({id:Date.now(),prospectId:p.id,action:'AI-drafted outbound outreach',status:'Pending',subject:draft.subject,body:draft.body,package:`TABLESIDE GROWTH — AI OUTREACH DRAFT\n\nBusiness: ${p.business}\n\nSUBJECT\n${draft.subject}\n\nCUSTOMER-FACING DRAFT\n${draft.body}\n\nAUTHORIZATION\nNOT SENT. Explicit human review and authorization required.`});state.activity.unshift(`${new Date().toLocaleString()} — AI prepared outreach for ${p.business} — NOT SENT — awaiting approval`);save();}catch(error){t.status='Error';state.activity.unshift(`${new Date().toLocaleString()} — AI draft failed for ${p.business}: ${error.message} — nothing sent`);save();}}
function loadApproval(id){const a=state.approvals.find(x=>x.id===id);if(!a)return;normalizeApproval(a);state.selected=a.prospectId;state.selectedApproval=a.id;workingDraft.value=a.body;showTab('drafts');save();}
function saveLoadedDraft(){if(!state.selectedApproval)return alert('Load a pending approval first.');const a=state.approvals.find(x=>x.id===state.selectedApproval);if(!a)return alert('Approval not found.');if(a.status!=='Pending')return alert('Only pending approvals can be edited.');const body=workingDraft.value.trim();if(!body)return alert('Draft cannot be empty.');normalizeApproval(a);a.body=body;delete a.reviewFingerprint;const p=state.prospects.find(x=>x.id===a.prospectId);if(p)a.package=buildInternalPackage(p,body);log(`Saved outreach draft for ${p?.business||'prospect'} — review required again`);}
async function approve(id){return alert('Authorization module is still loading. Try again.');}
function reject(id){const a=state.approvals.find(x=>x.id===id);if(!a||a.status!=='Pending')return;a.status='Rejected';const p=state.prospects.find(x=>x.id===a.prospectId);log(`Rejected outbound outreach for ${p?.business||'prospect'}`);}
async function copyDraft(){try{await navigator.clipboard.writeText(workingDraft.value);log('Copied draft');}catch(e){alert('Copy failed. Select the text and copy manually.');}}
function openGmail(){const p=state.prospects.find(x=>x.id===state.selected);if(!p)return alert('Select a prospect first.');if(!p.email)return alert('This prospect has no public business email saved.');const body=workingDraft.value.trim();if(!body)return alert('No draft loaded.');const approval=state.selectedApproval?state.approvals.find(x=>x.id===state.selectedApproval):null;if(approval)normalizeApproval(approval);const subject=approval?.subject||`Quick question about ${p.business}`;const u='https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(p.email)+'&su='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);window.open(u,'_blank');log(`Opened Gmail compose for ${p.business} — manual preview only`);}
function makeClient(id){const p=state.prospects.find(x=>x.id===id);if(!p)return;if(!state.clients.find(x=>x.prospectId===id))state.clients.push({prospectId:id,business:p.business,status:'Active',revenue:0});p.status='Client';log(`Promoted ${p.business} to client`);}
function addRevenue(id){const c=state.clients.find(x=>x.prospectId===id);if(!c)return;const v=Number(prompt('Revenue amount:'));if(!Number.isFinite(v)||v<0)return;c.revenue+=v;state.revenue+=v;log(`Recorded $${v.toFixed(2)} revenue from ${c.business}`);}
function saveConfig(){state.dailyLimit=Math.max(1,Math.min(100,Number(dailyLimit.value)||10));save();}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tableside-growth-export.json';a.click();URL.revokeObjectURL(a.href);log('Exported data');}
function render(){state.approvals.forEach(normalizeApproval);document.getElementById('agentStatus').textContent=state.agent;sProspects.textContent=state.prospects.length;sContacted.textContent=state.prospects.filter(x=>x.status==='Contacted').length;sInterested.textContent=state.prospects.filter(x=>x.status==='Interested').length;sRevenue.textContent='$'+state.revenue.toFixed(2);dailyLimit.value=state.dailyLimit;prospectRows.innerHTML=state.prospects.map(p=>`<tr><td>${esc(p.business)}</td><td>${esc(p.city)}</td><td>${esc(p.status)}</td><td>${esc(p.email)}</td><td><button onclick="makeDraft(${p.id})">AI Draft</button><button onclick="queue(${p.id})">Queue</button><button class="secondary" onclick="setStatus(${p.id},'Contacted')">Contacted</button><button class="secondary" onclick="setStatus(${p.id},'Interested')">Interested</button><button class="secondary" onclick="makeClient(${p.id})">Client</button></td></tr>`).join('');taskRows.innerHTML=state.tasks.slice().reverse().map(t=>{const p=state.prospects.find(x=>x.id===t.prospectId);return `<tr><td>${esc(p?.business||'Unknown')}</td><td>${esc(t.task)}</td><td>${esc(t.status)}</td></tr>`;}).join('');approvalRows.innerHTML=state.approvals.map(a=>{const p=state.prospects.find(x=>x.id===a.prospectId);let actions;if(a.status==='Pending')actions=`<button onclick="loadApproval(${a.id})">Load</button><button onclick="approve(${a.id})">Review / Authorize</button><button class="secondary" onclick="reject(${a.id})">Reject</button>`;else if(a.status==='Sending')actions='<span>Sending…</span>';else actions=`<span>${esc(a.status)}</span>`;return `<tr><td>${esc(p?.business||'Unknown')}</td><td>${esc(a.action)}</td><td>${esc(a.status)}</td><td>${actions}</td></tr>`;}).join('');clientRows.innerHTML=state.clients.map(c=>`<tr><td>${esc(c.business)}</td><td>${esc(c.status)}</td><td>$${Number(c.revenue||0).toFixed(2)} <button onclick="addRevenue(${c.prospectId})">+ Revenue</button></td></tr>`).join('');document.getElementById('log').textContent=state.activity.join('\n');}
render();