import http from 'node:http';
import { authConfigured, loginOwner, loginAllowed, recordLoginFailure, clearLoginFailures, requireSession, logout } from './private/auth.js';
import { ensureOwner, getProspect, listProspects, createProspect, updateProspect, archiveProspect } from './private/prospects.js';
import { timeline, recordInbound, createFollowUp, setTaskStatus } from './private/followups.js';
import { prepareReplyDraft } from './private/reply-ai.js';
import { createDraft, authorizeDraft, consumeAuthorization } from './private/authorizations.js';
import { databaseConfigured } from './db/pool.js';
import { beginGmailOAuth, finishGmailOAuth, gmailStatus, disconnectGmail, findGmailReplies } from './private/gmail-oauth.js';

const PORT=Number(process.env.PORT||3000);const ORIGIN='https://gabenapoleone3-ai.github.io';const AI_TIMEOUT_MS=45000;
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function bodyJson(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>24000)throw new Error('Request too large');}if(!raw)return {};try{return JSON.parse(raw);}catch{throw new Error('Invalid JSON');}}
const text=(v,max)=>String(v||'').trim().slice(0,max);const confidence=v=>['low','medium','high'].includes(String(v||'').toLowerCase())?String(v).toLowerCase():'low';
function prospectFrom(input){const p={businessName:text(input.businessName,160),city:text(input.city,120),website:text(input.website,500),instagram:text(input.instagram,250),notes:text(input.notes,4000),research:text(input.research,10000)};if(!p.businessName)throw new Error('Business name is required');return p;}
function parseModelJson(output){const cleaned=String(output||'').replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim();if(!cleaned)throw new Error('AI returned no output');try{return JSON.parse(cleaned);}catch{throw new Error('AI returned invalid structured output');}}
function outputText(data){return data.output_text||(data.output||[]).flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||'';}
async function openAIRequest(payload,timeoutMs=AI_TIMEOUT_MS){if(!process.env.OPENAI_API_KEY)throw new Error('AI service is not configured');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,max_output_tokens:2200,...payload})});const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===429)throw new Error('AI_RATE_LIMIT');throw new Error(data?.error?.message||`AI request failed (${response.status})`);}return data;}catch(error){if(error?.name==='AbortError')throw new Error('AI request timed out');throw error;}finally{clearTimeout(timeout);}}
async function askOpenAI(prompt){return parseModelJson(outputText(await openAIRequest({input:prompt,max_output_tokens:1600})));}
function usedWebSources(data){const found=new Map();for(const item of data.output||[]){for(const s of item?.action?.sources||[]){if(s?.url)found.set(s.url,{url:s.url,title:text(s.title||'',240)});}for(const c of item?.content||[]){for(const a of c?.annotations||[]){const u=a?.url||a?.url_citation?.url;if(u)found.set(u,{url:u,title:text(a?.title||a?.url_citation?.title||'',240)});}}}return [...found.values()].slice(0,30);}
function canonicalUrl(value){try{const u=new URL(String(value||'').trim());u.hash='';u.search='';u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');let path=u.pathname.replace(/\/+$/,'')||'/';return `${u.hostname}${path}`.toLowerCase();}catch{return '';}}
function hostOf(value){try{return new URL(String(value||'').trim()).hostname.toLowerCase().replace(/^www\./,'');}catch{return '';}}
function businessTokens(name){return String(name||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>2&&!['the','and','cafe','coffee','restaurant','inc','ltd'].includes(x));}
function evidenceForCandidate(candidate,sources){const requested=Array.isArray(candidate?.sourceUrls)?candidate.sourceUrls:[];const requestedCanon=new Set(requested.map(canonicalUrl).filter(Boolean));const requestedHosts=new Set(requested.map(hostOf).filter(Boolean));const websiteHost=hostOf(candidate?.website);const instagramHost=hostOf(candidate?.instagram);const tokens=businessTokens(candidate?.businessName);const scored=[];for(const s of sources){const canon=canonicalUrl(s.url),host=hostOf(s.url),hay=`${s.title||''} ${s.url||''}`.toLowerCase();let score=0;if(canon&&requestedCanon.has(canon))score+=8;if(host&&requestedHosts.has(host))score+=5;if(websiteHost&&host===websiteHost)score+=6;if(instagramHost&&host===instagramHost)score+=4;score+=Math.min(3,tokens.filter(t=>hay.includes(t)).length);if(score>0)scored.push({s,score});}scored.sort((a,b)=>b.score-a.score);return [...new Map(scored.map(x=>[x.s.url,x.s])).values()].slice(0,5);}
async function discoverProspects(input){const city=text(input.city,120),category=text(input.category,120)||'independent restaurants, cafes, and local service businesses',limit=Math.max(1,Math.min(5,Number(input.limit)||5));if(!city)throw new Error('Discovery city is required');const prompt=[`Find up to ${limit} currently operating ${category} in ${city} for legitimate business prospecting.`,'Prefer independent/local businesses. Use public web search. Verify each candidate is actually in the requested city.','For each candidate return the business name, city, category, official website if found, official Instagram if found, a public business email only if explicitly published, identity confidence, one short reason it is a candidate, and source URLs actually used.','Do not invent owners, emails, contacts, weaknesses, performance claims, or private information. Return only medium/high-confidence identities. Leave unverifiable fields blank.','Keep research concise: stop once enough evidence exists to identify up to the requested number of businesses.','Return ONLY JSON: {"prospects":[{"businessName":string,"city":string,"category":string,"website":string,"instagram":string,"publicEmail":string,"identityConfidence":"medium|high","whyCandidate":string,"sourceUrls":[string]}]}.'].join('\n');const data=await openAIRequest({tools:[{type:'web_search',search_context_size:'low'}],input:prompt,max_output_tokens:1800},55000);const result=parseModelJson(outputText(data)),sources=usedWebSources(data);const prospects=Array.isArray(result.prospects)?result.prospects.slice(0,limit).map(p=>{const matched=evidenceForCandidate(p,sources);return {businessName:text(p?.businessName,160),city:text(p?.city||city,120),category:text(p?.category,160),website:text(p?.website,500),instagram:text(p?.instagram,250),publicEmail:text(p?.publicEmail,250),identityConfidence:confidence(p?.identityConfidence),whyCandidate:text(p?.whyCandidate,500),sourceUrls:matched.map(s=>s.url)};}).filter(p=>p.businessName&&['medium','high'].includes(p.identityConfidence)&&p.sourceUrls.length):[];return {city,category,prospects,sources};}
async function researchProspect(input){const p=prospectFrom(input);const prompt=['Research this public business prospect for TableSide Growth using web search.','Goal: identify the correct business and collect current public facts useful for preparing a legitimate, personalized first-contact business audit.','Prefer the business official website and official social profiles for business-controlled facts. Use reputable public listings or review platforms only as secondary corroboration.','Do not infer private information. Do not guess when businesses share similar names. Treat identity as low confidence unless name plus location, official URL, phone/address, or another strong identifier matches.','Only state a fact when it is supported by a source actually found during this search. Mark uncertain or conflicting details as unknown.','Do not generate sales claims or pretend a suggestion is a fact.','Return ONLY JSON: {"identityConfidence":"low|medium|high","matchedBusiness":string,"facts":[{"fact":string,"sourceUrls":[string]}],"unknowns":[string],"researchSummary":string}.',`Starting prospect details: ${JSON.stringify({businessName:p.businessName,city:p.city,website:p.website,instagram:p.instagram,notes:p.notes})}`].join('\n');const data=await openAIRequest({tools:[{type:'web_search',search_context_size:'medium'}],input:prompt,max_output_tokens:1800},60000);const result=parseModelJson(outputText(data));const sources=usedWebSources(data);const facts=Array.isArray(result.facts)?result.facts.slice(0,15).map(f=>{const matched=evidenceForCandidate({businessName:p.businessName,website:p.website,instagram:p.instagram,sourceUrls:f?.sourceUrls},sources);return {fact:text(f?.fact,600),sourceUrls:matched.map(s=>s.url).slice(0,4)};}).filter(f=>f.fact&&f.sourceUrls.length):[];return {identityConfidence:confidence(result.identityConfidence),matchedBusiness:text(result.matchedBusiness,240),facts,unknowns:Array.isArray(result.unknowns)?result.unknowns.slice(0,12).map(x=>text(x,500)).filter(Boolean):[],researchSummary:text(result.researchSummary,3000),sources};}
async function analyzeProspect(input){const p=prospectFrom(input);const result=await askOpenAI(['Analyze this business prospect for TableSide Growth using ONLY the supplied evidence.','Never invent business facts. When evidence is insufficient, mark the fact unknown and lower confidence.','Separate verified facts from hypotheses/recommendations. Recommendations must be practical customer-growth experiments, not guarantees.','Return ONLY JSON: {"identityConfidence":"low|medium|high","verifiedFacts":[string],"unknowns":[string],"opportunities":[{"idea":string,"evidence":string,"confidence":"low|medium|high"}],"researchSummary":string}.',`Evidence: ${JSON.stringify(p)}`].join('\n'));return {identityConfidence:confidence(result.identityConfidence),verifiedFacts:Array.isArray(result.verifiedFacts)?result.verifiedFacts.slice(0,12).map(x=>text(x,500)).filter(Boolean):[],unknowns:Array.isArray(result.unknowns)?result.unknowns.slice(0,12).map(x=>text(x,500)).filter(Boolean):[],opportunities:Array.isArray(result.opportunities)?result.opportunities.slice(0,8).map(o=>({idea:text(o?.idea,800),evidence:text(o?.evidence,800),confidence:confidence(o?.confidence)})).filter(o=>o.idea):[],researchSummary:text(result.researchSummary,3000)};}
async function generateDraft(input){const p=prospectFrom(input);const analysis=input.analysis&&typeof input.analysis==='object'?input.analysis:null;const draft=await askOpenAI(['Write a concise legitimate first-contact email for TableSide Growth.','Offer a short free customer-growth audit, but make the email sound like a normal person wrote it rather than a sales template.','Use plain conversational language, short sentences, and one clear call to action. Avoid corporate or AI-sounding phrases such as leverage, optimize, response measures, low-lift, unlock, maximize, or growth solutions.','Use at most one or two verified business details when they make the opening genuinely specific.','Use only verified facts supplied below. Never invent facts, results, urgency, guarantees, or claims that something was reviewed when it was not.','Keep it warm, professional, non-pushy, and preferably 70-110 words. Sign: Gabe, TableSide Growth.','Return ONLY JSON with exactly two string fields: subject and body.',`Prospect: ${JSON.stringify(p)}`,`Analysis: ${JSON.stringify(analysis)}`].join('\n'));const subject=text(draft.subject,180),body=text(draft.body,4000);if(!subject||!body)throw new Error('AI returned an incomplete draft');return {subject,body};}
async function privateOwner(req,res){const session=await requireSession(req);if(!session){json(res,401,{error:'Authentication required'});return null;}return ensureOwner(session.email,'TableSide Growth Owner');}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const path=url.pathname;if(origin===ORIGIN)res.setHeader('Access-Control-Allow-Origin',ORIGIN);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS'){if(origin&&origin!==ORIGIN)return json(res,403,{error:'Origin not allowed'});return res.writeHead(204).end();}if(req.method==='GET'&&path==='/health')return json(res,200,{ok:true,service:'tableside-growth-ai',aiConfigured:Boolean(process.env.OPENAI_API_KEY),databaseConfigured:databaseConfigured(),privateAuthConfigured:authConfigured(),capabilities:['prospect-discovery','public-business-research','prospect-analysis','draft-generation','private-prospect-storage','conversation-timeline','human-followups','ai-reply-preparation','server-side-email-authorization','login-rate-limiting','private-ai-routes','backend-authorized-gmail-send','trusted-outbound-audit','persistent-private-sessions','server-side-gmail-oauth'],discoveryEvidence:'normalized-v4-output-capped'});if(origin&&origin!==ORIGIN)return json(res,403,{error:'Origin not allowed'});try{
if(req.method==='POST'&&path==='/api/private/login'){const input=await bodyJson(req);if(!loginAllowed(req,input.email))return json(res,429,{error:'Too many failed login attempts. Try again later.'});const session=await loginOwner(input.email,input.password);if(!session){recordLoginFailure(req,input.email);return json(res,401,{error:'Invalid login'});}clearLoginFailures(req,input.email);return json(res,200,{ok:true,session});}if(req.method==='POST'&&path==='/api/private/logout'){await logout(req);return json(res,200,{ok:true});}if(req.method==='GET'&&path==='/api/private/session'){const session=await requireSession(req);return session?json(res,200,{ok:true,email:session.email,expiresAt:new Date(session.expiresAt).toISOString()}):json(res,401,{error:'Authentication required'});}
if(req.method==='GET'&&path==='/api/private/gmail/connect'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,{url:await beginGmailOAuth(owner.id)});}
if(req.method==='GET'&&path==='/api/private/gmail/status'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,await gmailStatus(owner.id));}
if(req.method==='POST'&&path==='/api/private/gmail/replies'){const owner=await privateOwner(req,res);if(!owner)return;const input=await bodyJson(req);return json(res,200,{replies:await findGmailReplies(owner.id,input.email,input.maxResults)});}
if(req.method==='POST'&&path==='/api/private/gmail/disconnect'){const owner=await privateOwner(req,res);if(!owner)return;await disconnectGmail(owner.id);return json(res,200,{ok:true});}
if(req.method==='GET'&&path==='/api/private/gmail/oauth/callback'){const code=url.searchParams.get('code'),state=url.searchParams.get('state');if(!code||!state)return json(res,400,{error:'Missing OAuth callback parameters'});const connected=await finishGmailOAuth(code,state);res.writeHead(302,{Location:'https://gabenapoleone3-ai.github.io/tableside-growth/private/?gmail=connected'});return res.end();}
if(path==='/api/private/prospects'){const owner=await privateOwner(req,res);if(!owner)return;if(req.method==='GET')return json(res,200,{prospects:await listProspects(owner.id)});if(req.method==='POST')return json(res,201,{prospect:await createProspect(owner.id,await bodyJson(req))});}
let match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})$/i);if(match){const owner=await privateOwner(req,res);if(!owner)return;if(req.method==='PATCH'){const prospect=await updateProspect(owner.id,match[1],await bodyJson(req));return prospect?json(res,200,{prospect}):json(res,404,{error:'Prospect not found'});}if(req.method==='DELETE'){const archived=await archiveProspect(owner.id,match[1]);return archived?json(res,200,{ok:true}):json(res,404,{error:'Prospect not found'});}}
match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})\/timeline$/i);if(match&&req.method==='GET'){const owner=await privateOwner(req,res);if(!owner)return;const data=await timeline(owner.id,match[1]);return data?json(res,200,data):json(res,404,{error:'Prospect not found'});}
match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})\/prepare-reply$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const prospect=await getProspect(owner.id,match[1]);if(!prospect)return json(res,404,{error:'Prospect not found'});const data=await timeline(owner.id,match[1]);const draft=await prepareReplyDraft({askOpenAI,prospect,communications:data.communications});return json(res,200,{draft});}
match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})\/drafts$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const draft=await createDraft(owner.id,match[1],await bodyJson(req));return draft?json(res,201,{draft}):json(res,404,{error:'Prospect not found'});}
match=path.match(/^\/api\/private\/drafts\/([0-9a-f-]{36})\/authorize$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const authorization=await authorizeDraft(owner.id,match[1],await bodyJson(req));return authorization?json(res,200,{authorization}):json(res,404,{error:'Draft not found'});}
match=path.match(/^\/api\/private\/authorizations\/([0-9a-f-]{36})\/consume$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const authorizedMessage=await consumeAuthorization(owner.id,match[1],await bodyJson(req));return authorizedMessage?json(res,200,{authorizedMessage}):json(res,404,{error:'Authorization not found'});}
match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})\/communications\/(inbound|outbound)$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const input=await bodyJson(req);const data=match[2]==='inbound'?await recordInbound(owner.id,match[1],input):await recordOutbound(owner.id,match[1],input);return data?json(res,201,data):json(res,404,{error:'Prospect not found'});}
match=path.match(/^\/api\/private\/prospects\/([0-9a-f-]{36})\/followups$/i);if(match&&req.method==='POST'){const owner=await privateOwner(req,res);if(!owner)return;const data=await createFollowUp(owner.id,match[1],await bodyJson(req));return data?json(res,201,{task:data}):json(res,404,{error:'Prospect not found'});}
match=path.match(/^\/api\/private\/tasks\/([0-9a-f-]{36})$/i);if(match&&req.method==='PATCH'){const owner=await privateOwner(req,res);if(!owner)return;const data=await setTaskStatus(owner.id,match[1],text((await bodyJson(req)).status,40));return data?json(res,200,{task:data}):json(res,404,{error:'Task not found'});}
if(req.method==='POST'&&path==='/api/private/discover-prospects'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,await discoverProspects(await bodyJson(req)));}if(req.method==='POST'&&path==='/api/private/research-prospect'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,await researchProspect(await bodyJson(req)));}if(req.method==='POST'&&path==='/api/private/analyze-prospect'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,await analyzeProspect(await bodyJson(req)));}if(req.method==='POST'&&path==='/api/private/generate-draft'){const owner=await privateOwner(req,res);if(!owner)return;return json(res,200,await generateDraft(await bodyJson(req)));}}catch(error){const message=error instanceof Error?error.message:'Request failed';if(message==='AI_RATE_LIMIT')return json(res,429,{error:'AI request is temporarily rate-limited. Nothing was sent.'});return json(res,/required|large|invalid JSON|invalid prospect|invalid task|changed after review|authorization|exact message/i.test(message)?400:500,{error:message});}return json(res,404,{error:'Not found'});});server.listen(PORT,'0.0.0.0',()=>console.log(`TableSide Growth AI backend listening on ${PORT}`));
