import http from 'node:http';
const PORT=Number(process.env.PORT||3000);const ORIGIN='https://gabenapoleone3-ai.github.io';
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));}
async function bodyJson(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>24000)throw new Error('Request too large');}return raw?JSON.parse(raw):{};}
const text=(v,max)=>String(v||'').trim().slice(0,max);
function prospectFrom(input){const p={businessName:text(input.businessName,160),city:text(input.city,120),website:text(input.website,500),instagram:text(input.instagram,250),notes:text(input.notes,4000),research:text(input.research,8000)};if(!p.businessName)throw new Error('Business name is required');return p;}
async function askOpenAI(prompt){if(!process.env.OPENAI_API_KEY)throw new Error('AI service is not configured');const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,input:prompt})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'AI request failed');const output=data.output_text||(data.output||[]).flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;if(!output)throw new Error('AI returned no output');return JSON.parse(output.replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim());}
async function analyzeProspect(input){const p=prospectFrom(input);const result=await askOpenAI(['Analyze this business prospect for TableSide Growth using ONLY the supplied evidence.','Do not claim to have visited a website, social profile, reviews, menu, store, or other source unless its actual contents are included in research or notes.','Never invent business facts. When evidence is insufficient, mark the fact unknown and lower confidence.','Separate verified facts from hypotheses/recommendations. Recommendations must be practical customer-growth experiments, not guarantees.','Return ONLY JSON: {"identityConfidence":"low|medium|high","verifiedFacts":[string],"unknowns":[string],"opportunities":[{"idea":string,"evidence":string,"confidence":"low|medium|high"}],"researchSummary":string}.',`Evidence: ${JSON.stringify(p)}`].join('\n'));return {identityConfidence:text(result.identityConfidence,12),verifiedFacts:Array.isArray(result.verifiedFacts)?result.verifiedFacts.slice(0,12).map(x=>text(x,500)):[],unknowns:Array.isArray(result.unknowns)?result.unknowns.slice(0,12).map(x=>text(x,500)):[],opportunities:Array.isArray(result.opportunities)?result.opportunities.slice(0,8).map(o=>({idea:text(o?.idea,800),evidence:text(o?.evidence,800),confidence:text(o?.confidence,12)})):[],researchSummary:text(result.researchSummary,3000)};}
async function generateDraft(input){const p=prospectFrom(input);const analysis=input.analysis&&typeof input.analysis==='object'?input.analysis:null;const draft=await askOpenAI(['Write a concise legitimate first-contact email for TableSide Growth.','Offer a short free customer-growth audit.','Use only verified facts supplied below. Do not turn hypotheses or recommendations into statements of fact.','Never invent facts, results, urgency, guarantees, or claims that something was reviewed when it was not.','If evidence is weak, keep the email general rather than guessing.','Keep it natural, professional, non-pushy, and under 130 words. Sign: Gabe, TableSide Growth.','Return ONLY JSON with exactly two string fields: subject and body.',`Prospect: ${JSON.stringify(p)}`,`Analysis: ${JSON.stringify(analysis)}`].join('\n'));return {subject:text(draft.subject,180),body:text(draft.body,4000)};}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin',ORIGIN);res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.writeHead(204).end();if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,service:'tableside-growth-ai',aiConfigured:Boolean(process.env.OPENAI_API_KEY),capabilities:['prospect-analysis','draft-generation']});try{if(req.method==='POST'&&req.url==='/api/analyze-prospect')return json(res,200,await analyzeProspect(await bodyJson(req)));if(req.method==='POST'&&req.url==='/api/generate-draft')return json(res,200,await generateDraft(await bodyJson(req)));}catch(error){const message=error instanceof Error?error.message:'Request failed';return json(res,/required|large|JSON/i.test(message)?400:500,{error:message});}return json(res,404,{error:'Not found'});});
server.listen(PORT,'0.0.0.0',()=>console.log(`TableSide Growth AI backend listening on ${PORT}`));