import http from 'node:http';
const PORT=Number(process.env.PORT||3000);const ORIGIN='https://gabenapoleone3-ai.github.io';const AI_TIMEOUT_MS=30000;
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
async function bodyJson(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>24000)throw new Error('Request too large');}if(!raw)return {};try{return JSON.parse(raw);}catch{throw new Error('Invalid JSON');}}
const text=(v,max)=>String(v||'').trim().slice(0,max);const confidence=v=>['low','medium','high'].includes(String(v||'').toLowerCase())?String(v).toLowerCase():'low';
function prospectFrom(input){const p={businessName:text(input.businessName,160),city:text(input.city,120),website:text(input.website,500),instagram:text(input.instagram,250),notes:text(input.notes,4000),research:text(input.research,8000)};if(!p.businessName)throw new Error('Business name is required');return p;}
function parseModelJson(output){const cleaned=String(output||'').replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim();if(!cleaned)throw new Error('AI returned no output');try{return JSON.parse(cleaned);}catch{throw new Error('AI returned invalid structured output');}}
async function askOpenAI(prompt){if(!process.env.OPENAI_API_KEY)throw new Error('AI service is not configured');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,input:prompt})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||`AI request failed (${response.status})`);const output=data.output_text||(data.output||[]).flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;return parseModelJson(output);}catch(error){if(error?.name==='AbortError')throw new Error('AI request timed out');throw error;}finally{clearTimeout(timeout);}}
async function analyzeProspect(input){const p=prospectFrom(input);const result=await askOpenAI(['Analyze this business prospect for TableSide Growth using ONLY the supplied evidence.','Do not claim to have visited a website, social profile, reviews, menu, store, or other source unless its actual contents are included in research or notes.','Never invent business facts. When evidence is insufficient, mark the fact unknown and lower confidence.','Separate verified facts from hypotheses/recommendations. Recommendations must be practical customer-growth experiments, not guarantees.','Return ONLY JSON: {"identityConfidence":"low|medium|high","verifiedFacts":[string],"unknowns":[string],"opportunities":[{"idea":string,"evidence":string,"confidence":"low|medium|high"}],"researchSummary":string}.',`Evidence: ${JSON.stringify(p)}`].join('\n'));return {identityConfidence:confidence(result.identityConfidence),verifiedFacts:Array.isArray(result.verifiedFacts)?result.verifiedFacts.slice(0,12).map(x=>text(x,500)).filter(Boolean):[],unknowns:Array.isArray(result.unknowns)?result.unknowns.slice(0,12).map(x=>text(x,500)).filter(Boolean):[],opportunities:Array.isArray(result.opportunities)?result.opportunities.slice(0,8).map(o=>({idea:text(o?.idea,800),evidence:text(o?.evidence,800),confidence:confidence(o?.confidence)})).filter(o=>o.idea):[],researchSummary:text(result.researchSummary,3000)};}
async function generateDraft(input){const p=prospectFrom(input);const analysis=input.analysis&&typeof input.analysis==='object'?input.analysis:null;const draft=await askOpenAI(['Write a concise legitimate first-contact email for TableSide Growth.','Offer a short free customer-growth audit.','Use only verified facts supplied below. Do not turn hypotheses or recommendations into statements of fact.','Never invent facts, results, urgency, guarantees, or claims that something was reviewed when it was not.','If evidence is weak, keep the email general rather than guessing.','Keep it natural, professional, non-pushy, and under 130 words. Sign: Gabe, TableSide Growth.','Return ONLY JSON with exactly two string fields: subject and body.',`Prospect: ${JSON.stringify(p)}`,`Analysis: ${JSON.stringify(analysis)}`].join('\n'));const subject=text(draft.subject,180),body=text(draft.body,4000);if(!subject||!body)throw new Error('AI returned an incomplete draft');return {subject,body};}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;if(origin===ORIGIN)res.setHeader('Access-Control-Allow-Origin',ORIGIN);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS'){if(origin&&origin!==ORIGIN)return json(res,403,{error:'Origin not allowed'});return res.writeHead(204).end();}if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,service:'tableside-growth-ai',aiConfigured:Boolean(process.env.OPENAI_API_KEY),capabilities:['prospect-analysis','draft-generation']});if(origin&&origin!==ORIGIN)return json(res,403,{error:'Origin not allowed'});try{if(req.method==='POST'&&req.url==='/api/analyze-prospect')return json(res,200,await analyzeProspect(await bodyJson(req)));if(req.method==='POST'&&req.url==='/api/generate-draft')return json(res,200,await generateDraft(await bodyJson(req)));}catch(error){const message=error instanceof Error?error.message:'Request failed';return json(res,/required|large|invalid JSON/i.test(message)?400:500,{error:message});}return json(res,404,{error:'Not found'});});
server.listen(PORT,'0.0.0.0',()=>console.log(`TableSide Growth AI backend listening on ${PORT}`));