const API='https://tableside-ai-backend-production.up.railway.app';
let token=sessionStorage.getItem('tableside_private_token')||'';
const $=id=>document.getElementById(id);
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data;}
function showApp(on){$('login').classList.toggle('hidden',on);$('app').classList.toggle('hidden',!on);$('logout').classList.toggle('hidden',!on);}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function loadProspects(){const {prospects}=await request('/api/private/prospects');$('rows').innerHTML=prospects.map(p=>`<tr><td><strong>${esc(p.businessName)}</strong><br><span class="muted">${esc(p.city)}</span></td><td>${esc(p.status)}</td><td>${esc(p.publicEmail||'—')}<br><span class="muted">${esc(p.website||'')}</span></td><td>${esc(p.nextAction||'—')}<br><span class="muted">${p.nextActionAt?esc(new Date(p.nextActionAt).toLocaleString()):''}</span></td><td><div class="actions"><button class="secondary" data-action="status" data-id="${p.id}">Status</button><button class="secondary" data-action="next" data-id="${p.id}">Next action</button><button class="secondary" data-action="archive" data-id="${p.id}">Archive</button></div></td></tr>`).join('');$('empty').classList.toggle('hidden',prospects.length>0);}
async function restore(){if(!token)return showApp(false);try{const s=await request('/api/private/session');$('sessionInfo').textContent=`Signed in as ${s.email}`;showApp(true);await loadProspects();}catch{token='';sessionStorage.removeItem('tableside_private_token');showApp(false);}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginStatus').textContent='Signing in…';try{const d=await request('/api/private/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});token=d.session.token;sessionStorage.setItem('tableside_private_token',token);$('password').value='';$('loginStatus').textContent='';await restore();}catch(err){$('loginStatus').textContent=err.message;$('loginStatus').className='err';}});
$('logout').onclick=async()=>{try{await request('/api/private/logout',{method:'POST'});}catch{}token='';sessionStorage.removeItem('tableside_private_token');showApp(false);};
$('refresh').onclick=()=>loadProspects().catch(e=>alert(e.message));
$('prospectForm').addEventListener('submit',async e=>{e.preventDefault();$('saveStatus').textContent='Saving…';try{await request('/api/private/prospects',{method:'POST',body:JSON.stringify({businessName:$('businessName').value,city:$('city').value,publicEmail:$('publicEmail').value,website:$('website').value,instagram:$('instagram').value,status:$('status').value,nextAction:$('nextAction').value,nextActionAt:$('nextActionAt').value||null,notes:$('notes').value})});e.target.reset();$('saveStatus').textContent='Saved to private database.';await loadProspects();}catch(err){$('saveStatus').textContent=err.message;$('saveStatus').className='err';}});
$('rows').addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;try{if(b.dataset.action==='archive'){if(!confirm('Archive this prospect? This does not contact anyone.'))return;await request(`/api/private/prospects/${b.dataset.id}`,{method:'DELETE'});}else if(b.dataset.action==='status'){const status=prompt('Status: new, researching, draft_ready, contacted, replied, interested, client, closed');if(!status)return;await request(`/api/private/prospects/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:status.trim().toLowerCase()})});}else{const nextAction=prompt('What should happen next?');if(nextAction===null)return;await request(`/api/private/prospects/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({nextAction})});}await loadProspects();}catch(err){alert(err.message);}});
restore();